from django.db import models

# Create your models here.
class MensTennisMatch(models.Model):
    tourney_id = models.CharField(max_length=50)
    tourney_name = models.CharField(max_length=100)
    surface = models.CharField(max_length=20)
    draw_size = models.IntegerField(null=True, blank=True)
    tourney_level = models.CharField(max_length=10)
    tourney_date = models.DateField()
    match_num = models.IntegerField()
    best_of = models.IntegerField()
    round = models.CharField(max_length=10)
    minutes = models.IntegerField(null=True, blank=True)
    winner_id = models.IntegerField()
    winner_seed = models.IntegerField(null=True, blank=True)
    winner_entry = models.CharField(max_length=10, null=True, blank=True)
    winner_name = models.CharField(max_length=100)
    winner_hand = models.CharField(max_length=1, null=True, blank=True)
    winner_ht = models.IntegerField(null=True, blank=True)
    winner_ioc = models.CharField(max_length=3)
    winner_age = models.IntegerField(null=True, blank=True)
    loser_id = models.IntegerField()
    loser_seed = models.IntegerField(null=True, blank=True)
    loser_entry = models.CharField(max_length=10, null=True, blank=True)
    loser_name = models.CharField(max_length=100)
    loser_hand = models.CharField(max_length=1, null=True, blank=True)
    loser_ht = models.IntegerField(null=True, blank=True)
    loser_ioc = models.CharField(max_length=3)
    loser_age = models.IntegerField(null=True, blank=True)
    winner_odds = models.FloatField(null=True, blank=True)
    loser_odds = models.FloatField(null=True, blank=True)
    w1 = models.IntegerField(null=True, blank=True)
    w2 = models.IntegerField(null=True, blank=True)
    w3 = models.IntegerField(null=True, blank=True)
    w4 = models.IntegerField(null=True, blank=True)
    w5 = models.IntegerField(null=True, blank=True)
    w_ace = models.IntegerField(null=True, blank=True)
    w_df = models.IntegerField(null=True, blank=True)
    w_svpt = models.IntegerField(null=True, blank=True)
    w_1stIn = models.IntegerField(null=True, blank=True)
    w_1stWon = models.IntegerField(null=True, blank=True)
    w_2ndWon = models.IntegerField(null=True, blank=True)
    w_SvGms = models.IntegerField(null=True, blank=True)
    w_bpSaved = models.IntegerField(null=True, blank=True)
    w_bpFaced = models.IntegerField(null=True, blank=True)
    l1 = models.IntegerField(null=True, blank=True)
    l2 = models.IntegerField(null=True, blank=True)
    l3 = models.IntegerField(null=True, blank=True)
    l4 = models.IntegerField(null=True, blank=True)
    l5 = models.IntegerField(null=True, blank=True)
    l_ace = models.IntegerField(null=True, blank=True)
    l_df = models.IntegerField(null=True, blank=True)
    l_svpt = models.IntegerField(null=True, blank=True)
    l_1stIn = models.IntegerField(null=True, blank=True)
    l_1stWon = models.IntegerField(null=True, blank=True)
    l_2ndWon = models.IntegerField(null=True, blank=True)
    l_SvGms = models.IntegerField(null=True, blank=True)
    l_bpSaved = models.IntegerField(null=True, blank=True)
    l_bpFaced = models.IntegerField(null=True, blank=True)
    winner_rank = models.IntegerField(null=True, blank=True)
    loser_rank = models.IntegerField(null=True, blank=True)

class WomensTennisMatch(models.Model):
    tourney_id = models.CharField(max_length=50)
    tourney_name = models.CharField(max_length=100)
    surface = models.CharField(max_length=20)
    draw_size = models.IntegerField(null=True, blank=True)
    tourney_level = models.CharField(max_length=10)
    tourney_date = models.DateField()
    match_num = models.IntegerField()
    best_of = models.IntegerField()
    round = models.CharField(max_length=10)
    minutes = models.IntegerField(null=True, blank=True)
    winner_id = models.IntegerField()
    winner_seed = models.IntegerField(null=True, blank=True)
    winner_entry = models.CharField(max_length=10, null=True, blank=True)
    winner_name = models.CharField(max_length=100)
    winner_hand = models.CharField(max_length=1, null=True, blank=True)
    winner_ht = models.IntegerField(null=True, blank=True)
    winner_ioc = models.CharField(max_length=3)
    winner_age = models.IntegerField(null=True, blank=True)
    loser_id = models.IntegerField()
    loser_seed = models.IntegerField(null=True, blank=True)
    loser_entry = models.CharField(max_length=10, null=True, blank=True)
    loser_name = models.CharField(max_length=100)
    loser_hand = models.CharField(max_length=1, null=True, blank=True)
    loser_ht = models.IntegerField(null=True, blank=True)
    loser_ioc = models.CharField(max_length=3)
    loser_age = models.IntegerField(null=True, blank=True)
    winner_odds = models.FloatField(null=True, blank=True)
    loser_odds = models.FloatField(null=True, blank=True)
    w1 = models.IntegerField(null=True, blank=True)
    w2 = models.IntegerField(null=True, blank=True)
    w3 = models.IntegerField(null=True, blank=True)
    w4 = models.IntegerField(null=True, blank=True)
    w5 = models.IntegerField(null=True, blank=True)
    w_ace = models.IntegerField(null=True, blank=True)
    w_df = models.IntegerField(null=True, blank=True)
    w_svpt = models.IntegerField(null=True, blank=True)
    w_1stIn = models.IntegerField(null=True, blank=True)
    w_1stWon = models.IntegerField(null=True, blank=True)
    w_2ndWon = models.IntegerField(null=True, blank=True)
    w_SvGms = models.IntegerField(null=True, blank=True)
    w_bpSaved = models.IntegerField(null=True, blank=True)
    w_bpFaced = models.IntegerField(null=True, blank=True)
    l1 = models.IntegerField(null=True, blank=True)
    l2 = models.IntegerField(null=True, blank=True)
    l3 = models.IntegerField(null=True, blank=True)
    l4 = models.IntegerField(null=True, blank=True)
    l5 = models.IntegerField(null=True, blank=True)
    l_ace = models.IntegerField(null=True, blank=True)
    l_df = models.IntegerField(null=True, blank=True)
    l_svpt = models.IntegerField(null=True, blank=True)
    l_1stIn = models.IntegerField(null=True, blank=True)
    l_1stWon = models.IntegerField(null=True, blank=True)
    l_2ndWon = models.IntegerField(null=True, blank=True)
    l_SvGms = models.IntegerField(null=True, blank=True)
    l_bpSaved = models.IntegerField(null=True, blank=True)
    l_bpFaced = models.IntegerField(null=True, blank=True)
    winner_rank = models.IntegerField(null=True, blank=True)
    loser_rank = models.IntegerField(null=True, blank=True)

class MensPlayer(models.Model):
    #player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id
    player_id = models.IntegerField()
    player_name = models.CharField(max_length=100)
    player_slug = models.CharField(max_length=100)
    player_hand = models.CharField(max_length=1, null=True, blank=True)
    player_dob = models.DateField()
    player_ioc = models.CharField(max_length=3)
    player_ht = models.IntegerField(null=True, blank=True)
    player_sofa_id = models.IntegerField()
    player_active = models.BooleanField(null=False)

class WomensPlayer(models.Model):
    player_id = models.IntegerField()
    player_name = models.CharField(max_length=100)
    player_slug = models.CharField(max_length=100)
    player_hand = models.CharField(max_length=1, null=True, blank=True)
    player_dob = models.DateField()
    player_ioc = models.CharField(max_length=3)
    player_ht = models.IntegerField(null=True, blank=True)
    player_sofa_id = models.IntegerField()
    player_active = models.BooleanField(null=False)

class MensFullEloStats(models.Model):
    player_id = models.IntegerField(null=True, blank=True)
    player_name = models.CharField(max_length=100)
    player_slug = models.CharField(max_length=100, null=True, blank=True)
    player_last_game = models.DateField()
    player_match_number= models.IntegerField()
    player_matches_played = models.IntegerField()
    elo_rating = models.IntegerField()
    point_elo_rating = models.IntegerField()
    game_elo_rating = models.IntegerField()
    set_elo_rating = models.IntegerField()
    service_game_elo_rating = models.IntegerField()
    return_game_elo_rating = models.IntegerField()
    tie_break_elo_rating = models.IntegerField()

class MensHardEloStats(models.Model):
    player_id = models.IntegerField(null=True, blank=True)
    player_name = models.CharField(max_length=100)
    player_slug = models.CharField(max_length=100, null=True, blank=True)
    player_last_game = models.DateField()
    player_match_number= models.IntegerField()
    player_matches_played = models.IntegerField()
    elo_rating = models.IntegerField()
    point_elo_rating = models.IntegerField()
    game_elo_rating = models.IntegerField()
    set_elo_rating = models.IntegerField()
    service_game_elo_rating = models.IntegerField()
    return_game_elo_rating = models.IntegerField()
    tie_break_elo_rating = models.IntegerField()

class MensClayEloStats(models.Model):
    player_id = models.IntegerField(null=True, blank=True)
    player_name = models.CharField(max_length=100)
    player_slug = models.CharField(max_length=100, null=True, blank=True)
    player_last_game = models.DateField()
    player_match_number= models.IntegerField()
    player_matches_played = models.IntegerField()
    elo_rating = models.IntegerField()
    point_elo_rating = models.IntegerField()
    game_elo_rating = models.IntegerField()
    set_elo_rating = models.IntegerField()
    service_game_elo_rating = models.IntegerField()
    return_game_elo_rating = models.IntegerField()
    tie_break_elo_rating = models.IntegerField()
    
class MensGrassEloStats(models.Model):
    player_id = models.IntegerField(null=True, blank=True)
    player_name = models.CharField(max_length=100)
    player_slug = models.CharField(max_length=100, null=True, blank=True)
    player_last_game = models.DateField()
    player_match_number= models.IntegerField()
    player_matches_played = models.IntegerField()
    elo_rating = models.IntegerField()
    point_elo_rating = models.IntegerField()
    game_elo_rating = models.IntegerField()
    set_elo_rating = models.IntegerField()
    service_game_elo_rating = models.IntegerField()
    return_game_elo_rating = models.IntegerField()
    tie_break_elo_rating = models.IntegerField()

class WomensFullEloStats(models.Model):
    player_id = models.IntegerField(null=True, blank=True)
    player_name = models.CharField(max_length=100)
    player_slug = models.CharField(max_length=100, null=True, blank=True)
    player_last_game = models.DateField()
    player_match_number= models.IntegerField()
    player_matches_played = models.IntegerField()
    elo_rating = models.IntegerField()
    point_elo_rating = models.IntegerField()
    game_elo_rating = models.IntegerField()
    set_elo_rating = models.IntegerField()
    service_game_elo_rating = models.IntegerField()
    return_game_elo_rating = models.IntegerField()
    tie_break_elo_rating = models.IntegerField()

class WomensHardEloStats(models.Model):
    player_id = models.IntegerField(null=True, blank=True)
    player_name = models.CharField(max_length=100)
    player_slug = models.CharField(max_length=100, null=True, blank=True)
    player_last_game = models.DateField()
    player_match_number= models.IntegerField()
    player_matches_played = models.IntegerField()
    elo_rating = models.IntegerField()
    point_elo_rating = models.IntegerField()
    game_elo_rating = models.IntegerField()
    set_elo_rating = models.IntegerField()
    service_game_elo_rating = models.IntegerField()
    return_game_elo_rating = models.IntegerField()
    tie_break_elo_rating = models.IntegerField()

class WomensClayEloStats(models.Model):
    player_id = models.IntegerField(null=True, blank=True)
    player_name = models.CharField(max_length=100)
    player_slug = models.CharField(max_length=100, null=True, blank=True)
    player_last_game = models.DateField()
    player_match_number= models.IntegerField()
    player_matches_played = models.IntegerField()
    elo_rating = models.IntegerField()
    point_elo_rating = models.IntegerField()
    game_elo_rating = models.IntegerField()
    set_elo_rating = models.IntegerField()
    service_game_elo_rating = models.IntegerField()
    return_game_elo_rating = models.IntegerField()
    tie_break_elo_rating = models.IntegerField()
    
class WomensGrassEloStats(models.Model):
    player_id = models.IntegerField(null=True, blank=True)
    player_name = models.CharField(max_length=100)
    player_slug = models.CharField(max_length=100, null=True, blank=True)
    player_last_game = models.DateField()
    player_match_number= models.IntegerField()
    player_matches_played = models.IntegerField()
    elo_rating = models.IntegerField()
    point_elo_rating = models.IntegerField()
    game_elo_rating = models.IntegerField()
    set_elo_rating = models.IntegerField()
    service_game_elo_rating = models.IntegerField()
    return_game_elo_rating = models.IntegerField()
    tie_break_elo_rating = models.IntegerField()

class MensTennisMatchStats(models.Model):
    tourney_id = models.CharField(max_length=50)
    tourney_name = models.CharField(max_length=100)
    tourney_date = models.DateField()
    surface = models.CharField(max_length=20)
    best_of = models.IntegerField()
    match_num = models.IntegerField()
    
    a_player_id = models.IntegerField(null=True, blank=True)
    a_player_name = models.CharField(max_length=100)
    a_player_slug = models.CharField(max_length=100, null=True, blank=True)
    b_player_id = models.IntegerField(null=True, blank=True)
    b_player_name = models.CharField(max_length=100)
    b_player_slug = models.CharField(max_length=100, null=True, blank=True)
    a_elo_rating = models.IntegerField(null=True, blank=True)
    a_point_elo_rating = models.IntegerField(null=True, blank=True)
    a_game_elo_rating = models.IntegerField(null=True, blank=True)
    a_set_elo_rating = models.IntegerField(null=True, blank=True)
    a_service_game_elo_rating = models.IntegerField(null=True, blank=True)
    a_return_game_elo_rating = models.IntegerField(null=True, blank=True)
    a_tie_break_elo_rating = models.IntegerField(null=True, blank=True)
    a_surface_elo_rating = models.IntegerField(null=True, blank=True)
    a_surface_point_elo_rating = models.IntegerField(null=True, blank=True)
    a_surface_game_elo_rating = models.IntegerField(null=True, blank=True)
    a_surface_set_elo_rating = models.IntegerField(null=True, blank=True)
    a_surface_service_game_elo_rating = models.IntegerField(null=True, blank=True)
    a_surface_return_game_elo_rating = models.IntegerField(null=True, blank=True)
    a_surface_tie_break_elo_rating = models.IntegerField(null=True, blank=True)
    a_win_percent = models.FloatField(null=True, blank=True)
    a_serve_rating = models.FloatField(null=True, blank=True)
    a_return_rating = models.FloatField(null=True, blank=True)
    a_pressure_rating = models.FloatField(null=True, blank=True)
    a_avg_vs_elo = models.FloatField(null=True, blank=True)
    a_matches_played = models.IntegerField()

    b_elo_rating = models.IntegerField(null=True, blank=True)
    b_point_elo_rating = models.IntegerField(null=True, blank=True)
    b_game_elo_rating = models.IntegerField(null=True, blank=True)
    b_set_elo_rating = models.IntegerField(null=True, blank=True)
    b_service_game_elo_rating = models.IntegerField(null=True, blank=True)
    b_return_game_elo_rating = models.IntegerField(null=True, blank=True)
    b_tie_break_elo_rating = models.IntegerField(null=True, blank=True)
    b_surface_elo_rating = models.IntegerField(null=True, blank=True)
    b_surface_point_elo_rating = models.IntegerField(null=True, blank=True)
    b_surface_game_elo_rating = models.IntegerField(null=True, blank=True)
    b_surface_set_elo_rating = models.IntegerField(null=True, blank=True)
    b_surface_service_game_elo_rating = models.IntegerField(null=True, blank=True)
    b_surface_return_game_elo_rating = models.IntegerField(null=True, blank=True)
    b_surface_tie_break_elo_rating = models.IntegerField(null=True, blank=True)
    b_win_percent = models.FloatField(null=True, blank=True)
    b_serve_rating = models.FloatField(null=True, blank=True)
    b_return_rating = models.FloatField(null=True, blank=True)
    b_pressure_rating = models.FloatField(null=True, blank=True)
    b_avg_vs_elo = models.FloatField(null=True, blank=True)
    b_matches_played = models.IntegerField()

    a_b_win = models.IntegerField()
    a_odds = models.FloatField(null=True, blank=True)
    b_odds = models.FloatField(null=True, blank=True)

class WomensTennisMatchStats(models.Model):
    tourney_id = models.CharField(max_length=50)
    tourney_name = models.CharField(max_length=100)
    tourney_date = models.DateField()
    surface = models.CharField(max_length=20)
    best_of = models.IntegerField()
    match_num = models.IntegerField()
    a_player_id = models.IntegerField(null=True, blank=True)
    a_player_name = models.CharField(max_length=100)
    a_player_slug = models.CharField(max_length=100, null=True, blank=True)
    b_player_id = models.IntegerField(null=True, blank=True)
    b_player_name = models.CharField(max_length=100)
    b_player_slug = models.CharField(max_length=100, null=True, blank=True)
    a_elo_rating = models.IntegerField(null=True, blank=True)
    a_point_elo_rating = models.IntegerField(null=True, blank=True)
    a_game_elo_rating = models.IntegerField(null=True, blank=True)
    a_set_elo_rating = models.IntegerField(null=True, blank=True)
    a_service_game_elo_rating = models.IntegerField(null=True, blank=True)
    a_return_game_elo_rating = models.IntegerField(null=True, blank=True)
    a_tie_break_elo_rating = models.IntegerField(null=True, blank=True)
    a_surface_elo_rating = models.IntegerField(null=True, blank=True)
    a_surface_point_elo_rating = models.IntegerField(null=True, blank=True)
    a_surface_game_elo_rating = models.IntegerField(null=True, blank=True)
    a_surface_set_elo_rating = models.IntegerField(null=True, blank=True)
    a_surface_service_game_elo_rating = models.IntegerField(null=True, blank=True)
    a_surface_return_game_elo_rating = models.IntegerField(null=True, blank=True)
    a_surface_tie_break_elo_rating = models.IntegerField(null=True, blank=True)
    a_win_percent = models.FloatField(null=True, blank=True)
    a_serve_rating = models.FloatField(null=True, blank=True)
    a_return_rating = models.FloatField(null=True, blank=True)
    a_pressure_rating = models.FloatField(null=True, blank=True)
    a_avg_vs_elo = models.FloatField(null=True, blank=True)
    a_matches_played = models.IntegerField()

    b_elo_rating = models.IntegerField(null=True, blank=True)
    b_point_elo_rating = models.IntegerField(null=True, blank=True)
    b_game_elo_rating = models.IntegerField(null=True, blank=True)
    b_set_elo_rating = models.IntegerField(null=True, blank=True)
    b_service_game_elo_rating = models.IntegerField(null=True, blank=True)
    b_return_game_elo_rating = models.IntegerField(null=True, blank=True)
    b_tie_break_elo_rating = models.IntegerField(null=True, blank=True)
    b_surface_elo_rating = models.IntegerField(null=True, blank=True)
    b_surface_point_elo_rating = models.IntegerField(null=True, blank=True)
    b_surface_game_elo_rating = models.IntegerField(null=True, blank=True)
    b_surface_set_elo_rating = models.IntegerField(null=True, blank=True)
    b_surface_service_game_elo_rating = models.IntegerField(null=True, blank=True)
    b_surface_return_game_elo_rating = models.IntegerField(null=True, blank=True)
    b_surface_tie_break_elo_rating = models.IntegerField(null=True, blank=True)
    b_win_percent = models.FloatField(null=True, blank=True)
    b_serve_rating = models.FloatField(null=True, blank=True)
    b_return_rating = models.FloatField(null=True, blank=True)
    b_pressure_rating = models.FloatField(null=True, blank=True)
    b_avg_vs_elo = models.FloatField(null=True, blank=True)
    b_matches_played = models.IntegerField()
    
    a_b_win = models.IntegerField()