# Generated by Django 5.0.6 on 2024-08-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("render", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menstennismatch",
            name="loser_rank_points",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="menstennismatch",
            name="winner_rank_points",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="womenstennismatch",
            name="loser_rank_points",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="womenstennismatch",
            name="winner_rank_points",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
