# Generated by Django 5.0.6 on 2024-07-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("render", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menstennismatchstats",
            name="a_odds",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="menstennismatchstats",
            name="b_odds",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
