# Generated by Django 5.0.6 on 2024-07-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("render", "0003_auto_20240713_0414"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="player_hand",
            field=models.CharField(blank=True, default="U", max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="tennismatch",
            name="loser_hand",
            field=models.CharField(blank=True, default="U", max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="tennismatch",
            name="winner_hand",
            field=models.CharField(blank=True, default="U", max_length=1, null=True),
        ),
    ]
