# Generated by Django 5.0.6 on 2024-07-13 04:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("render", "0005_alter_player_player_hand_and_more"),
    ]

    operations = []
