# Generated by Django 5.0.6 on 2024-07-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("render", "0006_auto_20240713_0442"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="player_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="player",
            name="player_sofa_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="tennismatch",
            name="draw_size",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
