# Generated by Django 5.0.6 on 2024-07-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("render", "0009_menstennismatchstats_womenstennismatchstats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mensclayelostats",
            name="player_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mensclayelostats",
            name="player_slug",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="mensfullelostats",
            name="player_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mensfullelostats",
            name="player_slug",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="mensgrasselostats",
            name="player_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mensgrasselostats",
            name="player_slug",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="menshardelostats",
            name="player_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="menshardelostats",
            name="player_slug",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="womensclayelostats",
            name="player_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="womensclayelostats",
            name="player_slug",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="womensfullelostats",
            name="player_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="womensfullelostats",
            name="player_slug",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="womensgrasselostats",
            name="player_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="womensgrasselostats",
            name="player_slug",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="womenshardelostats",
            name="player_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="womenshardelostats",
            name="player_slug",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
